- id: '1702134691039'
  alias: Reload Templates on Restart
  description: Automatically reloads template entities after Home Assistant restarts.
  trigger:
  action:
  - service: homeassistant.reload_config_entry
    target:
      entity_id: sensor.formatted_received_traffic
    data: {}
