- id: '1697226060455'
  alias: Afvalmelding
  description: Melding dag voor afval
  trigger:
  - platform: time
    at: '18:00:00'
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.afvalinfo_afval_voor_morgen
      state: geen
  action:
  - service: notify.mobile_app_iphone_van_theo
    data:
      title: Afval morgen
      message: 'Afval morgen: {{states.sensor.afvalinfo_afval_voor_morgen.state}}'
  - service: persistent_notification.create
    data:
      title: Afval morgen
      message: 'Afval morgen: {{states.sensor.afvalinfo_afval_voor_morgen.state}}'
  - service: shell_command.ntfy
    data:
      topic: tvdsluijs_afval
      title: Afval morgen
      message: 'Afval morgen: {{states.sensor.afvalinfo_afval_voor_morgen.state}}'
  - service: notify.notify
    data:
      title: Afval morgen
      message: 'Afval morgen: {{states.sensor.afvalinfo_afval_voor_morgen.state}}'
  mode: single
- id: '1697274767250'
  alias: Stroom prijs lager dan 0.001
  description: Stroom prijs lager dan 0.001
  trigger:
  - platform: time_pattern
    hours: '*'
    minutes: '5'
  condition:
  - condition: time
    after: 06:00:00
    before: '23:00:00'
  - condition: numeric_state
    entity_id: sensor.volgend_uur_stroom_prijs_inkoop
    below: 0.001
    attribute: price
  action:
  - service: shell_command.ntfy
    data:
      topic: eprijzen_ondernul
      title: Stroom onder Nul
      markdown: 'Yes'
      message: "Om {{((now().timestamp()|int) +3600) | timestamp_custom(\"%H:00\")}}
        gaat de Inkoop \U0001F4A1 prijs naar € {{state_attr('sensor.volgend_uur_stroom_prijs_inkoop',
        'price') | round(3)}}\n"
  - service: notify.mobile_app_iphone_van_theo
    data:
      title: Stroom onder Nul
      message: "Om {{((now().timestamp()|int) +3600) | timestamp_custom(\"%H:00\")}}
        gaat de Inkoop \U0001F4A1 prijs naar € {{state_attr('sensor.volgend_uur_stroom_prijs_inkoop',
        'price') | round(3)}}\n"
      data:
        push:
          sound: claire-enhanced-de-stroomprijs-gaat-onder-nul.wav
  - service: persistent_notification.create
    data:
      title: Stroom onder Nul
      message: "Om {{((now().timestamp()|int) +3600) | timestamp_custom(\"%H:00\")}}
        gaat de Inkoop \U0001F4A1 prijs naar € {{state_attr('sensor.volgend_uur_stroom_prijs_inkoop',
        'price') | round(3)}}\n"
  - service: notify.notify
    data:
      title: Stroom onder Nul
      message: "Om {{((now().timestamp()|int) +3600) | timestamp_custom(\"%H:00\")}}
        gaat de Inkoop \U0001F4A1 prijs naar € {{state_attr('sensor.volgend_uur_stroom_prijs_inkoop',
        'price') | round(3)}}\n"
  mode: single
- id: '1698928890216'
  alias: 8 uur melding
  description: Ochtend melding
  trigger:
  - platform: time
    at: 08:00:00
  condition: []
  action:
  - service: notify.mobile_app_iphone_van_theo
    data:
      title: Ochtend prijzen melding
      message: "Inkoop prijs {{ now().strftime(\"%d %b `%y\") }} \n\U0001F4A1 laagste
        €. {{state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'min') | round(3)}} /
        kWh  \n\U0001F4A1 hoogste €. {{state_attr('sensor.nordpool_kwh_nl_eur_5_10_0',
        'max') | round(3)}} / kWh\n\U0001F525 Na 06u €. {{states('sensor.huidige_gas_prijs_inkoop')
        | round(3)}} / m3\n"
      data:
        url: /lovelace/energie-prijzen
        clickAction: /lovelace/energie-prijzen-vandaag
        push:
          sound: claire-enhanced-goedemorgen-hier-is-je-dagelijkse-energie-prijs-overzicht.wav
  - service: persistent_notification.create
    data:
      title: Ochtend prijzen melding
      message: "Inkoop prijs {{ now().strftime(\"%d %b `%y\") }} \n\U0001F4A1 laagste
        €. {{state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'min') | round(3)}} /
        kWh  \n\U0001F4A1 hoogste €. {{state_attr('sensor.nordpool_kwh_nl_eur_5_10_0',
        'max') | round(3)}} / kWh\n\U0001F525 Na 06u €. {{states('sensor.huidige_gas_prijs_inkoop')
        | round(3)}} / m3   \n"
      data:
        url: /lovelace/energie-prijzen
        clickAction: /lovelace/energie-prijzen-vandaag
  mode: single
- id: '1698929188698'
  alias: Change Shelly RGB based on electricity price 2
  description: Change Shelly RGB based on electricity price
  trigger:
  - platform: time_pattern
    hours: '*'
  condition: []
  action:
  - service: rest_command.shelly_rgb
    data:
      IP_address: 192.168.11.218
      status: 'on'
      color_r: "{% set price = state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'current_price')|float
        %} {% set min_price = state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'min')|float
        %} {% set max_price = state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'max')|float
        %} {% if price < 0 %}\n  0\n{% else %}\n  {% set scaled_price = ((price -
        min_price) / (max_price - min_price)) * 100 %}\n  {{ scaled_price }}\n{% endif
        %}\n"
      color_g: "{% set price = state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'current_price')|float
        %} {% set min_price = state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'min')|float
        %} {% set max_price = state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'max')|float
        %} {% if price < 0 %}\n  0\n{% else %}\n  {% set scaled_price = ((price -
        min_price) / (max_price - min_price)) * 100 %}\n  {{ 100 - scaled_price }}\n{%
        endif %}\n"
      color_b: "{% set price = state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'current_price')|float
        %} {% if price < 0 %}\n  {% set scaled_blue = ((0 - price) / 0.50) * 100 %}\n
        \ {{ [scaled_blue, 100]|min }}\n{% else %}\n  0\n{% endif %}\n"
      brightness: '80'
  - service: rest_command.shelly_rgb
    data:
      IP_address: 192.168.11.218
      status: 'off'
      color_r: "{% set price = state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'current_price')|float
        %} {% set min_price = state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'min')|float
        %} {% set max_price = state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'max')|float
        %} {% if price < 0 %}\n  0\n{% else %}\n  {% set scaled_price = ((price -
        min_price) / (max_price - min_price)) * 100 %}\n  {{ scaled_price }}\n{% endif
        %}\n"
      color_g: "{% set price = state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'current_price')|float
        %} {% set min_price = state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'min')|float
        %} {% set max_price = state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'max')|float
        %} {% if price < 0 %}\n  0\n{% else %}\n  {% set scaled_price = ((price -
        min_price) / (max_price - min_price)) * 100 %}\n  {{ 100 - scaled_price }}\n{%
        endif %}\n"
      color_b: "{% set price = state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'current_price')|float
        %} {% if price < 0 %}\n  {% set scaled_blue = ((0 - price) / 0.50) * 100 %}\n
        \ {{ [scaled_blue, 100]|min }}\n{% else %}\n  0\n{% endif %}\n"
      brightness: '40'
  mode: single
- id: '1700227258425'
  alias: Check Energieprijzen van Morgen en verzend bericht
  trigger:
  - platform: time_pattern
    hours: /1
    minutes: '0'
    seconds: '0'
  condition:
  - condition: time
    after: '12:00:00'
    before: '17:00:00'
  - condition: state
    entity_id: input_boolean.nordpool_message_sent
    state: 'off'
  - condition: template
    value_template: '{{ state_attr(''sensor.nordpool_kwh_nl_eur_5_10_0'', ''tomorrow_valid'')
      }}'
  action:
  - variables:
      formatted_message: "{% set raw_data = state_attr('sensor.nordpool_kwh_nl_eur_5_10_0',
        'raw_tomorrow') %} {% set ns = namespace(rows=[]) %} {% for i in range(12)
        %}\n  {% set start1 = raw_data[i].start %}\n  {% set start2 = raw_data[i+12].start
        %}\n  {% if start1 is string %}\n    {% set time1 = start1.split('T')[1][:5]
        %}\n    {% set time2 = start2.split('T')[1][:5] %}\n  {% else %}\n    {% set
        time1 = start1.strftime('%H:%M') %}\n    {% set time2 = start2.strftime('%H:%M')
        %}\n  {% endif %}\n  {% set value1 = '{:.3f}'.format(raw_data[i].value).replace('.',
        ',') %}\n  {% set value2 = '{:.3f}'.format(raw_data[i+12].value).replace('.',
        ',') %}\n  {% set row = time1 ~ ' € ' ~ value1 ~ ' ' ~ time2 ~ ' € ' ~ value2
        %}\n  {% set ns.rows = ns.rows + [row] %}\n{% endfor %} {{ ns.rows|join('\\n')
        }}\n"
  - service: notify.mobile_app_iphone_van_theo
    data:
      title: Stroom inkoop prijs van Morgen
      message: '{{ formatted_message }}'
      data:
        url: /lovelace/energie-prijzen
        clickAction: /lovelace/energie-prijzen-morgen
        push:
          sound: claire-enhanced-hier-zijn-de-stroomprijzen-van-morgen.wav
  - service: persistent_notification.create
    data:
      title: Stroom inkoop prijs van Morgen
      message: '{{ formatted_message }}'
  - service: input_boolean.turn_on
    entity_id: input_boolean.nordpool_message_sent
- id: '1700227453965'
  alias: Reset dagelijks Energieprijzen bericht
  description: Reset dagelijks Energieprijzen bericht
  trigger:
  - platform: time
    at: 00:01:00
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.nordpool_message_sent
- id: '1700299507647'
  alias: Check Nordpool and Send Message
  trigger:
  - platform: time_pattern
    hours: /1
    minutes: '0'
    seconds: '0'
  action:
  - variables:
      formatted_message: "{% set raw_data = state_attr('sensor.nordpool_kwh_nl_eur_5_10_0',
        'raw_today') %} {% set ns = namespace(rows=[]) %} {% for i in range(12) %}\n
        \ {% set start1 = raw_data[i].start %}\n  {% set start2 = raw_data[i+12].start
        %}\n  {% if start1 is string %}\n    {% set time1 = start1.split('T')[1][:5]
        %}\n    {% set time2 = start2.split('T')[1][:5] %}\n  {% else %}\n    {% set
        time1 = start1.strftime('%H:%M') %}\n    {% set time2 = start2.strftime('%H:%M')
        %}\n  {% endif %}\n  {% set value1 = '{:.3f}'.format(raw_data[i].value).replace('.',
        ',') %}\n  {% set value2 = '{:.3f}'.format(raw_data[i+12].value).replace('.',
        ',') %}\n  {% set row = time1 ~ ' € ' ~ value1 ~ ' ' ~ time2 ~ ' € ' ~ value2
        %}\n  {% set ns.rows = ns.rows + [row] %}\n{% endfor %} {{ ns.rows|join('\\n')
        }}\n"
  - service: notify.mobile_app_iphone_van_theo
    data:
      title: Stroom onder Nul
      message: '{{ formatted_message }}'
- id: '1700599535236'
  alias: Rijdt van parkeerplaats af
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.theo
      zone_entity: zone.parkeerplaats_theo_werk
      notify_device: 9e099f4d5e4686d31cbd80312ef907aa
- id: '1700599604048'
  alias: Jesse rijdt van werk weg
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.jesse
      zone_entity: zone.jesse_werk
      notify_device: 9e099f4d5e4686d31cbd80312ef907aa
- id: '1700599719039'
  alias: Rijdt van werk, Danielle
  description: Rijdt van werk, Danielle
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.danielle
      zone_entity: zone.danielle_werk
      notify_device: 9e099f4d5e4686d31cbd80312ef907aa
- id: '1700599774658'
  alias: Rijdt van school, Quinten
  description: Rijdt van school, Quinten
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.quinten
      zone_entity: zone.quinten_school
      notify_device: 9e099f4d5e4686d31cbd80312ef907aa
- id: '1700599826080'
  alias: Rijdt van school, Jesse
  description: Rijdt van school, Jesse
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.jesse
      zone_entity: zone.jesse_school
      notify_device: 9e099f4d5e4686d31cbd80312ef907aa
