homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
      - "/config"

frontend:
  themes: !include_dir_merge_named themes

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include templates.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml

binary_sensor:
  - platform: meteoalarm
    country: "netherlands"
    province: "Zeeland"
    language: nl-NL
  - platform: ping
    host: 192.168.11.89
    name: Epson Printer Online
    count: 1
    scan_interval: 60

rest_command:
  shelly_rgb:
    url: 'http://{{ IP_address }}/rpc/'
    method: POST
    headers:
      accept: "application/json, text/html"
    payload: '{"id": {{ range(1,100) | random }},"method": "PLUGS_UI.SetConfig","params": {"config": {"leds": {"mode": "switch","colors": {"switch:0": {"{{ status }}": {"rgb": [{{ color_r }},{{ color_g }},{{ color_b }}],"brightness" :{{ brightness }}}}}}}}}'
    content_type:  'application/json; charset=utf-8'

shell_command:
    ntfy: >
        curl
        -X POST
        --url 'https://ntfy.sh/{{ topic }}'
        --data '{{ message }}'
        --header 'X-Title: {{ title }}'
        --header 'X-Tags: {{ tags }}'
        --header 'X-Priority: {{ priority }}'
        --header 'X-Delay: {{ delay }}'
        --header 'X-Actions: {{ actions }}'
        --header 'X-Markdown: {{ markdown }}'
        --header 'X-Click: {{ click }}'
        --header 'X-Icon: {{ icon }}'

camera:
  - platform: ffmpeg
    name: SchuurCam
    input: !secret schuurcam
  - platform: ffmpeg
    name: StalCam
    input: !secret stalcam
  - platform: ffmpeg
    name: Doorbell
    input: !secret doorbel
  - platform: ffmpeg
    name: CatCam
    input: !secret catcam
  - platform: ffmpeg
    name: StalCam2
    input: !secret stalcam2
  - platform: buienradar

sensor:
# External IP
  - platform: rest
    scan_interval: 3600
    unique_id: external_ipv4
    resource: https://api.ipify.org?format=json
    method: GET
    json_attributes:
        - ip
# Ambee Pollen Sensor
  - platform: rest
    scan_interval: 3600
    unique_id: ambee_pollen
    resource: https://api.ambeedata.com/latest/pollen/by-lat-lng?lat=51.457072134927486&lng=3.850663722106284
    name: "Ambee Pollen"
    headers:
      content-type: "application/json"
      x-api-key: !secret ambeedata_api_key
    json_attributes_path: "$.data.['Risk']"
    json_attributes:
      - tree_pollen
      - grass_pollen
      - weed_pollen
# NordPool Stroom Prijzen Sensor
  - platform: nordpool
    region: "NL"
    currency: "EUR"
    VAT: False
    precision: 5
    price_in_cents: false
    price_type: kWh
# EnergyZero Gas Prijs Sensor
  - platform: rest
    unique_id: energyzero_gas_prijs_per_dag_restapi
    name: EnergyZero Gas prijs per dag
    resource: https://api.energyzero.nl/v1/energyprices
    scan_interval: 900
    value_template: OK
    params:
      fromDate: >
        {{(now().strftime('%Y-%m-%d')|as_datetime).isoformat()}}Z
      tillDate: >
        {{((now()+ timedelta(days=2)).strftime('%Y-%m-%d')|as_datetime).isoformat()}}Z
      interval: 4
      usageType: 3
      inclBtw: false
    json_attributes:
      - Prices
# Zelfbouw Temp/Humidity/Stof Sensor
  - platform: rest
    unique_id: outside_air_quality_temp
    name: outside_air_quality
    json_attributes:
      - sensordatavalues
    resource: http://192.168.11.154/data.json
    value_template: "OK"
# Afval Sensor
  - platform: afvalinfo
    id: ''
    resources:
      - type: gft
        friendly_name: Groente Fruit en Tuinafval
      - type: papier
        friendly_name: Papier
      - type: restafval
        friendly_name: Restafval
      - type: trash_type_today
        friendly_name: Afval voor vandaag
      - type: trash_type_tomorrow
        friendly_name: Afval voor morgen
    location: !secret location
    postcode: !secret postcode
    streetnumber: 20
    streetnumbersuffix: ''
    dateformat: '%d-%m-%Y'
    locale: 'nl'
    timespanindays: 365
    notrashtext: 'geen'
# Raspberry Pi Systeem Monitor Sensor
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: disk_use
      - type: disk_free
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: processor_use
      - type: processor_temperature
      - type: last_boot
# time date sensor
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'      