#===============================================================
## home assistand informatie
#===============================================================
homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
      - "/config"

frontend:
  themes: !include_dir_merge_named themes

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

#===============================================================
#http:
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

#===============================================================
# Text to speech
tts:
  - platform: google_translate
    language: 'nl'


#===============================================================
## Includes zodat deze lijst overzichtelijker blijft
#===============================================================
group: !include groups.yaml
automation: !include automations.yaml
automation mine: !include_dir_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include templates.yaml
input_number: !include input/input_number.yaml
input_select: !include input/input_select.yaml
input_boolean: !include input/input_boolean.yaml
sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
camera: !include_dir_merge_list camera/
# utility_meter: !include utility_meter/utility.yaml    NIEUW EERST TESTEN

rest_command:
  shelly_rgb:
    url: 'http://{{ IP_address }}/rpc/'
    method: POST
    headers:
      accept: "application/json, text/html"
    payload: '{"id": {{ range(1,100) | random }},"method": "PLUGS_UI.SetConfig","params": {"config": {"leds": {"mode": "switch","colors": {"switch:0": {"{{ status }}": {"rgb": [{{ color_r }},{{ color_g }},{{ color_b }}],"brightness" :{{ brightness }}}}}}}}}'
    content_type:  'application/json; charset=utf-8'

shell_command:
    ntfy: >
        curl
        -X POST
        --url 'https://ntfy.sh/{{ topic }}'
        --data '{{ message }}'
        --header 'X-Title: {{ title }}'
        --header 'X-Tags: {{ tags }}'
        --header 'X-Priority: {{ priority }}'
        --header 'X-Delay: {{ delay }}'
        --header 'X-Actions: {{ actions }}'
        --header 'X-Markdown: {{ markdown }}'
        --header 'X-Click: {{ click }}'
        --header 'X-Icon: {{ icon }}'
