# Afval Sensor
- platform: afvalinfo
  id: ''
  resources:
    - type: gft
      friendly_name: Groente Fruit en Tuinafval
    - type: papier
      friendly_name: Papier
    - type: restafval
      friendly_name: Restafval
    - type: trash_type_today
      friendly_name: Afval voor vandaag
    - type: trash_type_tomorrow
      friendly_name: Afval voor morgen
  location: !secret location
  postcode: !secret postcode
  streetnumber: 20
  streetnumbersuffix: ''
  dateformat: '%d-%m-%Y'
  locale: 'nl'
  timespanindays: 365
  notrashtext: 'geen'