### Camera Configuration in Home Assistant
#
# Author: Theo van der Sluijs
# Contact: info@itheo.tech
#
# Description: This configuration sets up several cameras in Home Assistant using the FFmpeg platform.
# It includes cameras for different locations such as the shed, stable, doorbell, and a special camera for a cat.
# Additionally, a weather camera is configured using the Buienradar platform.

# FFmpeg camera for the shed
- platform: ffmpeg
  name: garage_cam # Name of the camera
  input: !secret garage_cam # Input source, URL is stored in secrets.yaml

# FFmpeg camera for the doorbell
- platform: ffmpeg
  name: Doorbell # Name of the camera
  input: !secret doorbel # Input source, URL is stored in secrets.yaml

# FFmpeg camera for the cat
# - platform: ffmpeg
#   name: CatCam  # Name of the camera
#   input: !secret catcam  # Input source, URL is stored in secrets.yaml

# FFmpeg camera for the stable
- platform: ffmpeg
  name: stal_links_cam # Name of the camera
  input: !secret stal_links_cam # Input source, URL is stored in secrets.yaml

# Another FFmpeg camera for the stable
- platform: ffmpeg
  name: stal_rechts_cam # Name of the camera
  input: !secret stal_rechts_cam # Input source, URL is stored in secrets.yaml

# Another FFmpeg camera for the stable
- platform: ffmpeg
  name: stal_rechts_cam # Name of the camera
  input: !secret stal_rechts_cam # Input source, URL is stored in secrets.yaml

# Another FFmpeg camera for the stable
- platform: ffmpeg
  name: in_stal_cam # Name of the camera
  input: !secret in_stal_cam # Input source, URL is stored in secrets.yaml

# End of configuration
