### Tomorrow's Energy Prices Overview Automation
#
# Author: Theo van der Sluijs
# Contact: info@itheo.tech
#
# Description: This automation generates a message with tomorrow's electricity purchase prices each hour between 
# 12:00 PM and 5:00 PM. It only sends the message once per day, ensuring you're informed about the next day's prices.

alias: 'Energie prijzen : Overzicht morgen'  # Name of the automation
description: 'Deze automatisering genereert een bericht met de elektriciteitsinkoopprijzen van morgen. Het verzendt het bericht slechts één keer per dag, zodat u op de hoogte bent van de prijzen van de volgende dag'

# Trigger for the automation
trigger:
  - platform: time_pattern
    hours: /1  # Every hour
    minutes: "0"
    seconds: "0"

# Conditions to check before executing actions
condition:
  - condition: time
    after: "12:00:00"  # Only after 12:00 PM
    before: "17:00:00"  # And before 5:00 PM
  - condition: state
    entity_id: input_boolean.nordpool_message_sent
    state: "off"  # Ensures the message is sent only once per day
  - condition: template
    value_template: "{{ state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'tomorrow_valid') }}"  # Checks if tomorrow's data is valid

# Actions to perform if the condition is met
action:
  - variables:
      # Template logic to format the message with tomorrow's prices
      formatted_message: >-
        {% set raw_today = state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'raw_today') %}
        {% for i in range(12) %}
        € {{ '%0.3f' | format(raw_today[i].value) | replace('.', ',') }} - {{ raw_today[i].start.strftime('%H:%M') }}  € {{ '%0.3f' | format(raw_today[i+12].value) | replace('.', ',') }} - {{ raw_today[i+12].start.strftime('%H:%M') }}
        {% endfor %}

  - service: notify.mobile_app_iphone_van_theo
    data:
      title: Stroom inkoop prijs van Morgen
      message: "{{ formatted_message }}"
      data:
        url: /lovelace/energie-prijzen
        clickAction: /lovelace/energie-prijzen-morgen
        push:
          sound: claire-enhanced-hier-zijn-de-stroomprijzen-van-morgen.wav
  - service: persistent_notification.create
    data:
      title: Stroom inkoop prijs van Morgen
      message: "{{ formatted_message }}"
  - service: input_boolean.turn_on
    entity_id: input_boolean.nordpool_message_sent  # Marks that the message for the day has been sent

mode: single  # The automation runs in single mode (does not queue multiple instances)

# End of configuration