alias: "Energie prijzen : Overzicht morgen 2"
description: >-
  Deze automatisering genereert een bericht met de elektriciteitsinkoopprijzen
  van morgen. Het verzendt het bericht slechts één keer per dag, zodat u op de
  hoogte bent van de prijzen van de volgende dag
trigger:
  - platform: time_pattern
    hours: /1
    minutes: "0"
    seconds: "0"
condition:
  - condition: time
    after: "12:00:00"
    before: "17:00:00"
  - condition: state
    entity_id: input_boolean.nordpool_message_sent
    state: "off"
  - condition: template
    value_template: "{{ state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'tomorrow_valid') }}"
action:
  - variables:
      formatted_message: >-
        Kaal (Inkoop) prijzen 💡 per kWh
        {% set raw_today = state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'raw_today') %}

        ```
        {% for i in range(12) %}
        € {{ '%0.3f' | format(raw_today[i].value) | replace('.', ',') }} - {{ raw_today[i].start.strftime('%H:%M') }}  € {{ '%0.3f' |
        format(raw_today[i+12].value) | replace('.', ',') }} - {{ raw_today[i+12].start.strftime('%H:%M') }}
        {% endfor %}
        ```

        Kaal (Inkoop) prijzen 🔥 per m³
        ```
        €. {{ states('sensor.huidige_gas_prijs_all_in') | round(3) }} ({{ '%.3f' | format(states('sensor.huidige_gas_prijs') | float) }}) /m3
        ```
      formatted_title: 📈 Energie inkoop prijs van morgen
  - data:
      title: "{{ formatted_title }}"
      message: "{{ formatted_message }}"
      data:
        url: /lovelace/energie-prijzen
        clickAction: /lovelace/energie-prijzen-morgen
        push:
          sound: claire-enhanced-hier-zijn-de-stroomprijzen-van-morgen.wav
    action: notify.mobile_app_iphone_van_theo
  - data:
      title: "{{ formatted_title }}"
      message: "{{ formatted_message }}"
    action: persistent_notification.create
  - data:
      title: "{{ formatted_title }}"
      message: "{{ formatted_message }}"
    action: notify.telegram
  - entity_id: input_boolean.nordpool_message_sent
    action: input_boolean.turn_on
mode: single
