### Morning Energy Prices Notification Automation
#
# Author: Theo van der Sluijs
# Contact: info@itheo.tech
# Description: This automation sends a morning notification with the day's energy prices.
# It provides information on the lowest and highest electricity prices, as well as the current gas price after 6 AM.

alias: "Energie prijzen : Ochtend melding" # Name of the automation
description: "Deze automatisering stuurt een ochtendmelding met de energieprijzen van de dag. Het geeft informatie over de laagste en hoogste elektriciteitsprijzen, evenals de huidige gasprijs na 06.00 uur." # Description of the automation

# Trigger for the automation
trigger:
  - platform: time
    at: "08:00:00" # The automation runs at 8:00 AM

condition: [] # No conditions are set for this automation

# Actions to perform when the automation is triggered
action:
  - variables:
      formatted_message: >-
        💡 laagste €. {{ states('sensor.stroom_prijs_laagste_all_in') | round(3) }} ({{ '%.3f' | format(state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'min') | float) }}) /kWh
        💡 hoogste €. {{ states('sensor.stroom_prijs_hoogste_all_in') | round(3) }} ({{ '%.3f' | format(state_attr('sensor.nordpool_kwh_nl_eur_5_10_0', 'max') | float) }}) /kWh
        🔥 Na 06u  €. {{ states('sensor.huidige_gas_prijs_all_in') | round(3) }} ({{ '%.3f' | format(states('sensor.huidige_gas_prijs') | float) }}) /m3
      formatted_title: >-
        💶 Energie prijs {{ now().strftime("%d %b `%y") }}
  - service: notify.mobile_app_iphone_van_theo
    data:
      title: "{{formatted_title}}"
      message: "{{ formatted_message }}"
      data:
        url: /lovelace/energie-prijzen
        clickAction: /lovelace/energie-prijzen-vandaag
        push:
          sound: claire-enhanced-goedemorgen-hier-is-je-dagelijkse-energie-prijs-overzicht.wav
  - service: persistent_notification.create
    data:
      title: "{{formatted_title}}"
      message: "{{ formatted_message }}"
      data:
        url: /lovelace/energie-prijzen
        clickAction: /lovelace/energie-prijzen-vandaag

mode: single # The automation runs in single mode (does not queue multiple instances)

# End of configuration
