### Home Assistant Update Notification Automation
#
# Editor: Theo van der Sluijs
# Contact: info@itheo.tech
#
# Org Author: Huizebruin / https://github.com/huizebruin
#
# Description: This automation notifies when there is a new update available for Home Assistant. 
# It checks if the latest available version differs from the currently installed version and sends notifications accordingly.

alias: 'Systeem : Home Assistant update notificatie'
description: 'Deze automatisering stuurt een notificatie wanneer er een nieuwe update beschikbaar is voor Home Assistant. Het controleert of de laatst beschikbare versie verschilt van de momenteel geïnstalleerde versie en stuurt dienovereenkomstig meldingen.'

# Trigger for the automation
trigger:
  - platform: state
    entity_id: sensor.docker_hub_update_available  # Monitors the latest available version sensor

# Condition to check before executing actions
condition:
  - condition: template
    value_template: |-
      {{
        states('binary_sensor.docker_hub_update_available')
        !=
        states('sensor.current_version')
      }}  # Compares the latest version with the installed version
# Actions to perform if the condition is met
action:
  - service: notify.mobile_app_iphone_van_theo
    data:
      title: "\U0001F6A7 Home Assistant update \U0001F389"
      message: >-
        {% if is_state('sensor.potential_breaking_changes', '0') %}
          Er is een Home Assistant update beschikbaar. \U0001F389 Versie: {{ states('binary_sensor.docker_hub_update_available') }}.
        {% else %}
          Er is een Home Assistant update beschikbaar. Versie: {{ states('binary_sensor.docker_hub_update_available') }}.
        {% endif %}
  - service: notify.persistent_notification
    data:
      data_template:
        title: "\U0001F6A7 Home Assistant update"
        message: >-
          Er is een Home Assistant update voor Hass.io beschikbaar! Versie: {{ states('binary_sensor.docker_hub_update_available') }}.
        notification_id: hassio_upgrade

mode: single  # The automation runs in single mode (does not queue multiple instances)

# End of configuration